[package]
name = "miraland-validator"
description = "Blockchain for sovereign individuals living in Mirascape Horizon"
documentation = "https://docs.rs/miraland-validator"
default-run = "miraland-validator"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = { workspace = true }
console = { workspace = true }
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
fd-lock = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true, features = ["ipc"] }
jsonrpc-derive = { workspace = true }
jsonrpc-ipc-server = { workspace = true }
jsonrpc-server-utils = { workspace = true }
lazy_static = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
miraland-accounts-db = { workspace = true }
miraland-clap-utils = { workspace = true }
miraland-cli-config = { workspace = true }
miraland-core = { workspace = true }
miraland-download-utils = { workspace = true }
miraland-entry = { workspace = true }
miraland-faucet = { workspace = true }
miraland-genesis-utils = { workspace = true }
miraland-geyser-plugin-interface = { workspace = true }
miraland-geyser-plugin-manager = { workspace = true }
miraland-gossip = { workspace = true }
miraland-ledger = { workspace = true }
miraland-logger = { workspace = true }
miraland-metrics = { workspace = true }
miraland-net-utils = { workspace = true }
miraland-perf = { workspace = true }
miraland-poh = { workspace = true }
miraland-rpc = { workspace = true }
miraland-rpc-client = { workspace = true }
miraland-rpc-client-api = { workspace = true }
miraland-runtime = { workspace = true }
miraland-sdk = { workspace = true }
miraland-send-transaction-service = { workspace = true }
miraland-storage-bigtable = { workspace = true }
miraland-streamer = { workspace = true }
miraland-svm = { workspace = true }
miraland-test-validator = { workspace = true }
miraland-tpu-client = { workspace = true }
miraland-unified-scheduler-pool = { workspace = true }
miraland-version = { workspace = true }
miraland-vote-program = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
miraland-account-decoder = { workspace = true }
miraland-runtime = { workspace = true, features = ["dev-context-only-utils"] }
solarti-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
