[package]
name = "miraland-tokens"
description = "Blockchain for community beyond the horizon"
documentation = "https://docs.rs/miraland-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = "4.4.8"
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
indexmap = { workspace = true }
indicatif = { workspace = true }
miraland-account-decoder = { workspace = true }
miraland-clap-utils = { workspace = true }
miraland-cli-config = { workspace = true }
miraland-remote-wallet = { workspace = true, features = ["default"] }
miraland-rpc-client = { workspace = true, features = ["default"] }
miraland-rpc-client-api = { workspace = true }
miraland-sdk = { workspace = true }
miraland-transaction-status = { workspace = true }
miraland-version = { workspace = true }
pickledb = { workspace = true, features = ["yaml"] }
serde = { workspace = true, features = ["derive"] }
solarti-associated-token-account = { workspace = true }
solarti-token = { workspace = true, features = ["no-entrypoint"] }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
miraland-logger = { workspace = true }
miraland-streamer = { workspace = true }
miraland-test-validator = { workspace = true }
