[package]
name = "solana-tokens"
description = "Blockchain, Rebuilt for Scale"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
version = "1.14.7"
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.15.0"
csv = "1.3.0"
ctrlc = { version = "3.2.2", features = ["termination"] }
indexmap = "1.9.1"
indicatif = "0.16.2"
pickledb = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
solana-account-decoder = { path = "../account-decoder", version = "=1.14.7" }
solana-clap-utils = { path = "../clap-utils", version = "=1.14.7" }
solana-cli-config = { path = "../cli-config", version = "=1.14.7" }
solana-client = { path = "../client", version = "=1.14.7" }
solana-remote-wallet = { path = "../remote-wallet", version = "=1.14.7" }
solana-sdk = { path = "../sdk", version = "=1.14.7" }
solana-transaction-status = { path = "../transaction-status", version = "=1.14.7" }
solana-version = { path = "../version", version = "=1.14.7" }
spl-associated-token-account = { version = "=1.1.1" }
spl-token = { version = "=3.5.0", features = ["no-entrypoint"] }
tempfile = "3.3.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
solana-logger = { path = "../logger", version = "=1.14.7" }
solana-streamer = { path = "../streamer", version = "=1.14.7" }
solana-test-validator = { path = "../test-validator", version = "=1.14.7" }

[[bin]]
name = "miraland-tokens"
path = "src/main.rs"
