[package]
name = "miraland-poh-bench"
documentation = "https://docs.rs/miraland-poh-bench"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "4.4.8", features = ["cargo"] }
log = { workspace = true }
miraland-entry = { workspace = true }
miraland-logger = { workspace = true }
miraland-measure = { workspace = true }
miraland-perf = { workspace = true }
miraland-sdk = { workspace = true }
miraland-version = { workspace = true }
rayon = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
