[package]
name = "miraland-cargo-test-sbf"
description = "Execute all unit and integration tests after building with the Miraland SBF SDK"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
cargo_metadata = { workspace = true }
clap = { version = "4.4.8", features = ["cargo"] }
itertools = { workspace = true }
log = { workspace = true, features = ["std"] }
miraland-logger = { workspace = true }

[[bin]]
name = "cargo-test-sbf"
path = "src/main.rs"
