[package]
name = "miraland-zk-keygen"
description = """
Miraland privacy-related key generation utility

The tool currently supports two types of encryption keys that are used in the Solarti Token-2022 program:
  - ElGamal keypair that can be used for public key encryption
  - AES128 key that can be used for an authenticated symmetric encryption (e.g. AES-GCM-SIV)
"""
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true }
clap = { version = "4.4.11", features = ["cargo", "derive"] }
dirs-next = { workspace = true }
miraland-clap-v3-utils = { workspace = true }
miraland-cli-config = { workspace = true }
miraland-remote-wallet = { workspace = true, features = ["default"] }
miraland-sdk = { workspace = true }
miraland-version = { workspace = true }
miraland-zk-token-sdk = { workspace = true }
num_cpus = { workspace = true }
thiserror = { workspace = true }
tiny-bip39 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "miraland-zk-keygen"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
